# Usando a imagem base do Node.js
FROM node:14

# Definindo o diretório de trabalho dentro do container
WORKDIR /app

# Copiando os arquivos package.json e package-lock.json
COPY package*.json ./

# Instalando as dependências
RUN npm install

# Copiando o restante do código
COPY . .

# Expondo a porta que o backend vai rodar
EXPOSE 5000

# Rodando o servidor Express
CMD ["node", "index.js"]
