# Usando a imagem base do PostgreSQL
FROM postgres:13

# Definindo variáveis de ambiente para o banco de dados
ENV POSTGRES_USER=usuario
ENV POSTGRES_PASSWORD=senha
ENV POSTGRES_DB=gestao_imagens

# Expondo a porta que o PostgreSQL vai rodar
EXPOSE 5432
