name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

  deploy_postgresql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push PostgreSQL
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-postgresql:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-postgresql:latest
